name: build
on:
  # push, not master
  #push:
  #  branches-ignore:
  #    - 'master'

  # called from other workflows
  workflow_call:
    inputs:
      artifact-name:
        type: string
    secrets:
      URL:
        required: true
      SUPABASE_URL:
        required: true
      SUPABASE_ANON_KEY:
        required: true
      SUPABASE_SERVICE_KEY:
        required: true
  
  # run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        env:
          HOME_URL: ${{ secrets.URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: npm run build
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip build
        run: zip -qq -r function.zip .
        working-directory: apps/app/.next
      # - name: Zip build
      #   if: ${{ inputs.artifact-name }} != ''
      #   uses: montudor/action-zip@v1
      #   with:
      #     args: cd ./apps/app/.next && zip -qq -r ${{ inputs.artifact-name }}.zip .
      - name: Upload artifact
        if: ${{ inputs.artifact-name }} != ''
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ inputs.artifact-name }}.zip
          name: ${{ inputs.artifact-name }}